# Site settings
title: The EscCode
description: Linux, Bash Script, Proxmox, Docker, Windows Serwer 2012, PowerShell, VoIP, IPPBX, VoipSwitch, Python, Pandas, Google GSuit, Google Apps Script, SQL,
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: EscCode
user_description: Linux, Bash Script, Proxmox, Docker, Windows Serwer 2012, PowerShell, VoIP, IPPBX, VoipSwitch, Python, Pandas, Google GSuit, Google Apps Script, SQL.
user_title: IT Support Software Developer
email: theesccode@gmail.com
linkedin_username: https://www.linkedin.com/in/jacek-wieteska-b66b511b9/
github_username:  https://github.com/esccode/
facebook_username:  https://www.facebook.com/jacek.wieteska.184

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
