title : Elementary - keca13 Blog
name: 'Jacek Wieteska'
description: 'ipcall, Praca zlecona, IT , jw, keca13, VoIP, IPPBX, Python, Google Apps Script, Support'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'

collections:
  news:
    title: News
    default_open: false
    output: true
  posts:
    title: Oferta
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
