# Site settings
title: The EscCode
description: Ansible, BSA, Centreon, SCOM, CrowdStrike, SQL(HeidiSQL), VoIP( VoIPSwitch, Asterisk PBX, PLICBD, Elastix PBX, Wireshark, Askozia PBX, Yealink, 3CX), Python(Pandas,tkinter,fabric), Perl(basic level), Bash, Linux/Unix(CentOS, Ubuntu, debian), Proxmox, VirtualBox, MobaXterm, WinSCP , Kaspersky Serwer,  Visual Studio Code, Windows Server 2012(PowerShell), Dell PowerEdge, RaspberryPi, Exel-2019(lookup,vlookup,if,iferror,sumif,sumifs,countif...etc.),FritzBox, GitHub.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: EscCode
user_description: 

user_title: IT Support / Passion for programming
email: theesccode@gmail.com
linkedin_username: https://www.linkedin.com/in/jacek-wieteska-b66b511b9/
github_username:  https://github.com/esccode/
facebook_username:  https://www.facebook.com/jacek.wieteska.184

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
