title : Elementary - keca13 Blog
name: 'Support IT'
description: 'ipcall, help desk, IT, jw, keca13, VoIP, IPPBX, Python, Google Apps Script, Support'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Kontakt
featured_posts:
  - url: 'https://keca13.github.io/tasks'
    title: 'Zlecenie pracy'
  - url: 'https://keca13.github.io/contact'
    title: 'Kontakt'

collections:
  news:
    title: News
    default_open: false
    output: true
  posts:
    title: W czy moge pomóc?
    default_open: false
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
