title: "keca13"
email: "wieteskajacek.code@gmail.com"
ipcall: "https://ipcall.pl"
description: "IPCall, jw, keca13, VoIP, IPPBX, Python, Google Apps Script, Support" # this means to ignore newlines until "baseurl:"
  
baseurl: "/" # the subpath of your site, e.g. /blog

url: "https://keca13.github.io/" # the base hostname & protocol for your site
# Example Site settings

github_username:  "keca13"

#google_analytics: UA-NNNNNNNN-N

header_pages:
- index.md
- about.md
- rodo.md
- tasks.md
- contact.md

welcome: '<center><b><a href="https://keca13.github.io/contact">Zapraszam do kontaktu</a></b></center> <br> <center><b><a href="https://keca13.github.io/tasks">Zleć prace</a></b></center><hr>'
footer:  'follow me on <a href="https://github.com/keca13/">GitHub</a> | <a href="https://www.facebook.com/jacek.wieteska.184">Facebook</a> | <a href="https://keca13.github.io/feed.rss">RSS</a>'

style:  dark (default) #or light
#listen_for_clients_preferred_style: true # true or false (default)

collections:
  categories:
    output: true

plugins:
  - jekyll-seo-tag
