title : EscCode
name: 'EscCode'
description: 'IT, Support, Linux, Bash Script, Proxmox, PowerShell, VoIP, IPPBX, Python, Pandas, Google G Suit, Google Apps Script, SQL, Windows Serwer 2012, Git.'

markdown: kramdown
highlighter: rouge
javascript_enabled: true
 
featured_posts_title: contact
featured_posts:
  - url: 'https://esccode.github.io/tasks'
    title: 'Get me a job'
  - url: 'https://esccode.github.io/contact'
    title: 'Contact'

collections:
  news:
    title: News
    default_open: false
    output: true
  posts:
    title: How can I help you?
    default_open: false
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
