title: keca13
email: wieteskajacek.code@gmail.com
ipcall: https://ipcall.pl
description: keca13, VoIP, IPPBX, Python, Google Apps Script, Support, # this means to ignore newlines until "baseurl:"
  
baseurl: "/" # the subpath of your site, e.g. /blog

url: "https://github.com/keca13" # the base hostname & protocol for your site
# Example Site settings

github_username:  keca13

#google_analytics: UA-NNNNNNNN-N

header_pages:
- index.md
- about.md
- tasks.md
- rodo.md
- contact.md

footer: <center><p><a href="https://keca13.github.io/contact">Zapraszam do kontaktu!</a></p></center> 'follow me on <a href="https://github.com/keca13/">GitHub</a> | <a href="https://www.facebook.com/jacek.wieteska.184">Facebook</a>'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

collections:
  categories:
    output: true

plugins:
  - jekyll-seo-tag
