title: jw site
email: jw@4gns.net
description: > # this means to ignore newlines until "baseurl:"
  VoIP Administrator
baseurl: "" # the subpath of your site, e.g. /blog

url: "keca13.github.io" # the base hostname & protocol for your site
# Example Site settings

github_username:  keca13

#google_analytics: UA-NNNNNNNN-N

header_pages:
#  - index.md
  - about.md

footer: 'follow me on <a href="https://github.com/keca13/">github</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
